### ISSUE TITLE
dict merge doesn't create a deep copy

### ISSUE THREAD

**Issue by minrk** [Masterminds/sprig#120]
I have a case where I want a template to take an input dictionary and produce a copy, omitting a few keys at various levels deep in the hierarchy (in [this helm chart](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/3b4cbb4ca8a359823b63940f5afb4af980100571/jupyterhub/templates/hub/configmap.yaml)).

I ran into a snare, where I didn't realize that after merging two dictionaries, editing the merged dictionary can modify the originals:

```
{{- $values := pick .Values "auth" "other"}}
{{- /* trim secret values. Update here if new secrets are added! */ -}}
{{- /* make a copy of values.auth to avoid modifying the original */ -}}
{{- $_ := set $values "auth" (merge dict .Values.auth) }}
{{- $_ := set $values.auth "state" (omit $values.auth.state "cryptoKey") }}
```

Without that `set $values "auth" (merge dict .Values.auth)`,
the subsequent `set $values.auth "state"` would modify the *original* `.Values.auth.state`, which I found surprising.

Is there an existing mechanism to produce a deep copy of a dict, to ensure the original doesn't get modified?

**Comment by msonnabaum** [comment]
Just got bit by this as well. I definitely did not expect `merge` to mutate the first argument.

**Comment by multi-io** [comment]
Having the same issue currently, and it seems there's no workaround in a Helm context (since deepCopy() is also not available there). This is one more proof that mutable state is evil!

**Comment by msonnabaum** [comment]
@multi-io The workaround I've used is to always pass `dict` as the first argument to merge. 

I'm not sure the issue is deep vs shallow copy, but rather it just mutates the first argument. The semantics appear similar to javascript's `Object.assign`.

The docs hint at this behavior by calling the first argument `$dest`, but it could be much clearer.

**Comment by InvictusMB** [comment]
@msonnabaum 
This does not work for nested dictionaries/lists. New dictionary retains references to the children of the source dictionary.
Both merge and mergeOverwrite are perfect foot guns.

**Comment by InvictusMB** [comment]
For example, this code unintentionally modifies $src2:
```go
{{- $src1 := dict "a" "b" -}}	
{{- $src2 := dict "foo" (dict "c" "d") -}}
{{- $src3 := dict "foo" (dict "e" "f") -}}
{{- $dest := merge dict $src1 $src2 $src3 }}
```
Go playground: https://play.golang.org/p/Kx5z_8Z7uHH

**Comment by rv4242** [comment]
I agree with InvictusMB. This is a royal pain in the... feet. I'm trying to merge helm values for a set of resources, and keep accumulating values inside of replacing them.

**Comment by rv4242** [comment]
Does this comment indicate that changing the merge behavior would break existing helm charts?
https://github.com/helm/helm/issues/3486#issuecomment-364534501

**Comment by InvictusMB** [comment]
No, I don't think so. That one is about merging vs overriding behavior. This thread is about taking parameters by value rather than by reference and not introducing unexpected side effects.

**Comment by mattfarina** [comment]
My current thinking is that we need a deepCopy function (see #149). This way people who rely on the current behavior can have that while people who want a deep copy can have that as well.

**Comment by InvictusMB** [comment]
@mattfarina
I am OK with preserving the mutation of the first parameter which is a destination dictionary. But I still insist that all the source dictionaries must be guarded by `deepCopy`.
The current behavior introduces unexpected mutations that depend on the shape and order of objects and the bugs it makes possible are extremely hard to track down.
Moreover, I cannot think of any code that will depend on that behavior intentionally.

Troubleshooting things like https://github.com/Masterminds/sprig/issues/120#issuecomment-519439250 is no fun at all. It happened to me on a project with a huge spread out Helm configuration and challenged my sanity a lot. Only because I added another nested dictionary into one chart that depended on a piece of a shared boilerplate, a completely unrelated chart stopped working.
