### ISSUE TITLE
Depends on very old version of Masterminds/sevmer

### ISSUE THREAD

**Issue by alex-broad** [Masterminds/sprig#162]
Your glide.lock specifies:
```
- name: github.com/Masterminds/semver
version: 59c29afe1a994eacb71c833025ca7acf874bb1da
```
Which translates to v1.2.2 of semver. This causes dependency conflicts when any other library tries to use a more recent version of semver that supports `semver.Constraint`. Can this be updated to use the latest stable version of semver to resolve this please?

**Comment by alex-broad** [comment]
This is exacerbated by me vendoring 'dep' which pulls in a non-stable version of semver - so perhaps this issue is my end. It's still a version from 2016 in any case :)

**Comment by mattfarina** [comment]
This is where you will run into some problems. There are 3 major versions of semver. 1.x is used by many tools including Helm. 2x is a branch used by dep that contains an unreleased codebase. It has a different Go API from 1.x. Currently semver is working on 3.x which has a compatible Go API with 1.x but there are many changes aside from that.

The issue is most definitely with dep and two major versions.

**Comment by mattfarina** [comment]
It now depends on the latest release of semver for v3.
