### ISSUE TITLE
cannot use semver.Version as type *semver.Version in return argument

### ISSUE THREAD

**Issue by arslantopcu1** [Masterminds/sprig#178]
Hi 

I using your project my project, But Dockerfile build get error

# github.com/Masterminds/sprig
../github.com/Masterminds/sprig/semver.go:22:2: cannot use semver.Version as type *semver.Version in return argument

Dockerfile: FROM golang:1.11.5 AS builder

**Comment by gunsluo** [comment]
Yes, I have the same problem.

I fixed it.  you can use command like `GO111MODULE=on go build -o frep`

**Comment by saujanreshmi** [comment]
I had no issues yesterday but I am experiencing following issue today:

Dockerfile:
RUN go get github.com/Masterminds/sprig
# github.com/Masterminds/sprig
../../Masterminds/sprig/semver.go:22:2: cannot use semver.Version as type *semver.Version in return argument

**Comment by lee5i3** [comment]
Looks like it was broke in:
https://github.com/Masterminds/semver/commit/23f51de38a0866c5ef0bfc42b3f735c73107b700

Was returning *Version and was changed to return Version

**Comment by arslantopcu1** [comment]
> Yes, I have the same problem.
> 
> I fixed it. you can use command like `GO111MODULE=on go build -o frep` in your dockerfile.

Don't fixed because  while break docker build "go get -v"

**Comment by arslantopcu1** [comment]
FROM golang:1.11.5 AS builder

WORKDIR /go/src/pts-api

ADD . .
RUN go get -v
RUN CGO_ENABLED=0 GOOS=linux go build -o app .

break "go get -v" exit code

**Comment by mattfarina** [comment]
&tldr; the semver package now has the same Go interface it did for v1. The install problem should be gone.

The issue is that the semver package is updating to v3 and making major changes. But, using `go get` to install an application that uses it pulls from the tip of master in too many cases. Including all the `go get` install instructions. That means Go package API changes, even on new major version,  cause broken installations.

This is a problem with `go get`. But, I was able to alter semver to have the older v1 Go API (some functionality will be different). So, the install problems should Go away.
