### ISSUE TITLE
b64enc returns nil on empty string

### ISSUE THREAD

**Issue by mvandervliet** [Masterminds/sprig#219]
This issue relates to the use of `helm`, and corresponding issue: [helm#7205](https://github.com/helm/helm/issues/7205).

When used in a situation like the following, the `b64enc` function seemingly returns `nil`

```text
{{  .Values.foo | default "" | b64enc }}
```

The problem can be mitigated by 

```text
{{  .Values.foo | default "" | b64enc | default ("" | quote) }}
```

**Comment by karuppiah7890** [comment]
@mvandervliet Would you be interested to work on a fix for this issue? 😄

**Comment by mvandervliet** [comment]
I've reviewed this code here, and seems like the functionality in sprig is unchanged. Rather this is an issue related to new validations imposed by kubernetes. Closing

**Comment by kingdonb** [comment]
Is there another approach that works better than:

```
{{  .Values.foo | default "" | b64enc | default ("" | quote) }}
```
?

I am really glad I found this report because that was what I needed, but that's also pretty long and gnarly as far as incantations go. (our use case for this is a value `global.accesskey` and `global.secretkey` which are used in an S3 config section, and meant to be left blank if they are not needed (when IAM should be used instead). So, that's absolutely not relevant to sprig, and I'm sorry to resurrect a dead issue report, I'm fine with "not a bug" no followup needed, but did not find a lot of similar reports or how to handle this issue, now that those such new validations were imposed in kubernetes.

Is that crazy incantation exactly what you wound up using @mvandervliet ?
