### ISSUE TITLE
Walk the file system

### ISSUE THREAD

**Issue by Asaf-Federman** [Masterminds/sprig#343]
Enable walking on file system with sprig using os.readDir

**Comment by mattfarina** [comment]
This doesn't feel proper for being in the template engine (separation of concerns) and opens the door for security holes.

In the separation of concerns, the data to work with should be passed into the template. The app should provide the means to load it and pass it in to the templates for rendering.

This is because the app can put certain security restrictions into place. It can choose not to load something from the file system. Or restrict loading to just the current directory.

A template being able to load any directory could cause a template author to grab something in `/etc`. If this is distributed via something like Helm than an attacker could ex-filtrate details from someones system far too easily.

That's why I'm marking this as wontfix.
