### ISSUE TITLE
is this still supported?

### ISSUE THREAD

**Issue by caarlos0** [Masterminds/sprig#396]
Hey!

Thanks for this project!

It seems that it is abandoned though... I wonder if that's real, and if so, if there are any "blessed" forks - and if there isn't any, how do you feel about me creating one.

Thanks!

**Comment by 42atomys** [comment]
Exploring sprig for my projects, I've noticed it could benefit from updates and additional features. With this in mind, I'm developing an evolved version, [sprout](https://github.com/42atomys/sprout), to address these gaps by leveraging new Go functionalities and minimizing dependencies. This project aims to build on sprig’s legacy, maintaining compatibility with sprig v3.2.3 while planning for future enhancements.

@caarlos0, your insights could greatly benefit this initiative. Would you be interested in collaborating on sprout? Our goal is to offer a seamless transition for sprig users, enriching the library with more capabilities over time. Check out [sprout v0.1](https://github.com/42atomys/sprout/releases/tag/v0.1) for a glimpse of our foundation, promising no breaking changes with the potential for significant future growth.

I will start to add features from sprig issues and PR in few days (also because I need somes features for my projects).

See You All 💜

**Comment by caarlos0** [comment]
hey @42atomys, yes, happy to help 🙏

**Comment by 42atomys** [comment]
@caarlos0 awesome, I have created the issue one [42atomys/sprout#1](https://github.com/42atomys/sprout/issues/1) to discuss and collaborate all together 🚀 

Any others developes are welcome to grow together 🌱

**Comment by andig** [comment]
@mattfarina I've noticed you're still active in https://github.com/Masterminds/semver. A statement would be great if you want 👍🏻

**Comment by andig** [comment]
Per issue template:

```
<!--
Thank you for submitting an issue to sprig.

If you have a feature request than pull requests for those features are also appreciated.

Sprig is a maintained project. Triaging issue happens several times per year rather than daily or weekly.
-->
```

But it seems that a year has passed now.

**Comment by 42atomys** [comment]
This is why we ask and we start to maintain to free time to the creator and give faster feedback to devs 🍕

**Comment by andig** [comment]
@mattfarina it seems the community has at least in parts moved on to sprout. Would be great to get an update on your plans.

**Comment by mattfarina** [comment]
Sprig is still being maintained. There was a gap in active development. You should see Sprig maintained via several sprints each year. This most recent release added a new function, updated the dependency tree, and setup testing with the latest versions of Go. Future releases will add some new functions (though Sprig is not going to be a place for everyone's functions for all the things) and improved testing and docs.

**Comment by mattfarina** [comment]
There has been a new sprig release and we have a plan for regular work throughout the year. Closing this issue because things are supported.
