### ISSUE TITLE
index template function

### ISSUE THREAD

**Issue by endorama** [Masterminds/sprig#87]
Hello, I spent some time understanding how to extract the element at index `n` of an Array

Es:
```
arr := [1,2,3]
I want to get arr[1] => 2
```
I finally found the `index` function, but is not documented in the docs and I did't find it's declaration in the code.

The usage is 
```
{{ index arr 2 }}
```
and I found references in:
-  [list_test.go](https://github.com/Masterminds/sprig/blob/ded3565ee06df6d916eb8b0a5815c38c3494a20c/list_test.go)
- [string_test.go](https://github.com/Masterminds/sprig/blob/ded3565ee06df6d916eb8b0a5815c38c3494a20c/strings_test.go)

Where does it come from? Should be documented in the `list.md` doc file?

I'm sorry if it's something obvious, I'm new to go and sprig. I can provide a PR to the documentation if you point me in the right direction.

Thank you!

**Comment by mattfarina** [comment]
@endorama The `index` function isn't part of sprig. Rather, it's part of the go templating functions. The following link has more details - https://golang.org/pkg/text/template/#hdr-Functions. That's why we don't document it here.

If you have further questions please feel free to re-open the issue.
